version: "3"
services: 
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - PROXY_DOMAIN="code-server.${DOMAIN}"
    volumes:
      - $PWD/code-server-config/:/config
    ports:
      - 8443:8443
    restart: unless-stopped
    env_file: .env
    labels:
      traefik.enable: "True"
      traefik.http.routers.code_server.rule: "Host(`code-server.${DOMAIN}`)"
      traefik.http.routers.code_server.tls.certresolver: "letsencrypt"
      traefik.http.routers.code_server.tls.domains[0].main: "${DOMAIN}"
      traefik.http.routers.code_server.tls.domains[0].sans: "*.${DOMAIN}"
      traefik.http.routers.code_server.middlewares: "code_server_auth"
      traefik.http.services.code-server.loadbalancer.server.port: "8443"
      traefik.http.middlewares.code_server_auth.basicauth.users: "user:$$2y$$05$$LBZka/94dyb0S/ZPqN2ixeVy..2Sok0xruiw7AhwyrbsPNd.SLF.W"
  halls_desktop:
    image: piopirahl/docker-desktop:1.0.2
    container_name: halls-desktop 
    ports: 
      - 6901:6901
    volumes:
      - "$PWD/config/.config:/home/dockeruser/.config:rw"
    env_file: .env
    labels:
      traefik.enable: "True"
      traefik.http.routers.halls_desktop.rule: "Host(`halls-desktop.${DOMAIN}`)"
      traefik.http.routers.halls_desktop.tls.certresolver: "letsencrypt"
      traefik.http.routers.halls_desktop.tls.domains[0].main: "${DOMAIN}"
      traefik.http.routers.halls_desktop.tls.domains[0].sans: "*.${DOMAIN}"
      traefik.http.routers.halls_desktop.middlewares: "halls_desktop_auth"
      traefik.http.services.halls_desktop.loadbalancer.server.port: "6901"
      traefik.http.middlewares.halls_desktop_auth.basicauth.users: "user:$$2y$$05$$LBZka/94dyb0S/ZPqN2ixeVy..2Sok0xruiw7AhwyrbsPNd.SLF.W"
